### ISSUE TITLE
Kleine dingen welke nog gedaan moeten worden

### ISSUE THREAD

**Issue by NielsWarnaar** [leonvsc/Premaz#66]
- [ ] Placeholder voor postcode sign-up en max length (HTML)
- [ ] Image upload opschonen en naar adminpanel #23 
- [ ] Documenten updaten (voornamelijk het technisch ontwerp)
- [ ] Requirement analyse nalopen en updaten waar nodig
- [ ] Projectomschijving nalopen om te kijken of we aan alle eisen voldoen.
- [ ] Dezelfde items in de winkelwagen in een row zetten en quantity updaten #44 
- [ ] Price toevoegen aan de producten in de winkelwagen #44 
- [ ] Totalprice toevoegen aan de winkelwagen #44 
- [ ] Alle pagina's benaderbaar maken door door te klikken op andere pagina's
- [ ] Alle TODO'S in de code nalopen en evt. fixen
- [ ] Shoppingcart en product laten werken met controller ipv data
- [ ] Orderpagina informatie van de bestelling (producten) laten zien #36 
- [ ] Unit tests schrijven #28 
- [ ] Testraportages (github actions) #28 #46 
- [ ] front end maken #54 #15 
- [ ] taalswitcher #25 
- [ ] Order na bestelling toevoegen aan de DB #36 
- [ ] Na bestelling (betaling) winkelwagen van het account uit de db verwijderen #36 #44 
- [ ] Detailspagina (see details knop) (admin en klant) moeten de juiste data krijgen
- [ ] #60 
- [ ] #61 
- [ ] #62 
- [ ] #56
